development:
  adapter: postgresql
  encoding: unicode
  database: eurekajobs_development
  pool: 5
  username: janakiraman
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: eurekajobs_test
  pool: 5
  username: janakiraman
  password: 
